"""empty message

Revision ID: 83c6967437bf
Revises: 4460232c884f
Create Date: 2023-02-10 17:26:26.188716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83c6967437bf'
down_revision = '4460232c884f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites_characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('element_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('favorites_characters_planet_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'character', ['element_id'], ['id'])
        batch_op.drop_column('planet_id')

    with op.batch_alter_table('favorites_films', schema=None) as batch_op:
        batch_op.add_column(sa.Column('element_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('favorites_films_film_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'films', ['element_id'], ['id'])
        batch_op.drop_column('film_id')

    with op.batch_alter_table('favorites_planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('element_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('favorites_planets_planet_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'planet', ['element_id'], ['id'])
        batch_op.drop_column('planet_id')

    with op.batch_alter_table('favorites_species', schema=None) as batch_op:
        batch_op.add_column(sa.Column('element_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('favorites_species_species_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'species', ['element_id'], ['id'])
        batch_op.drop_column('species_id')

    with op.batch_alter_table('favorites_starships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('element_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('favorites_starships_starship_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'starships', ['element_id'], ['id'])
        batch_op.drop_column('starship_id')

    with op.batch_alter_table('favorites_vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('element_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('favorites_vehicles_vehicle_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'vehicles', ['element_id'], ['id'])
        batch_op.drop_column('vehicle_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites_vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorites_vehicles_vehicle_id_fkey', 'vehicles', ['vehicle_id'], ['id'])
        batch_op.drop_column('element_id')

    with op.batch_alter_table('favorites_starships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('starship_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorites_starships_starship_id_fkey', 'starships', ['starship_id'], ['id'])
        batch_op.drop_column('element_id')

    with op.batch_alter_table('favorites_species', schema=None) as batch_op:
        batch_op.add_column(sa.Column('species_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorites_species_species_id_fkey', 'species', ['species_id'], ['id'])
        batch_op.drop_column('element_id')

    with op.batch_alter_table('favorites_planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorites_planets_planet_id_fkey', 'planet', ['planet_id'], ['id'])
        batch_op.drop_column('element_id')

    with op.batch_alter_table('favorites_films', schema=None) as batch_op:
        batch_op.add_column(sa.Column('film_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorites_films_film_id_fkey', 'films', ['film_id'], ['id'])
        batch_op.drop_column('element_id')

    with op.batch_alter_table('favorites_characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorites_characters_planet_id_fkey', 'character', ['planet_id'], ['id'])
        batch_op.drop_column('element_id')

    # ### end Alembic commands ###
